
export const POSTS_REQUEST_DATA = 'POSTS_REQUEST_DATA'
export const POSTS_RECEIVE_DATA = 'POSTS_RECEIVE_DATA'
export const POSTS_RECEIVE_ERROR = 'POSTS_RECEIVE_ERROR'

export const BS_REQUEST_DATA = 'BS_REQUEST_DATA'
export const BS_RECEIVE_DATA = 'BS_RECEIVE_DATA'
export const BS_ERROR = 'BS_ERROR'
