
export const POSTS_REQUEST_DATA = 'POSTS_REQUEST_DATA'
export const POSTS_RECEIVE_DATA = 'POSTS_RECEIVE_DATA'
export const POSTS_RECEIVE_ERROR = 'POSTS_RECEIVE_ERROR'

export const BS_REQUEST_DATA = 'BS_REQUEST_DATA'
export const BS_RECEIVE_DATA = 'BS_RECEIVE_DATA'
export const BS_ERROR = 'BS_ERROR'

export const NOTES_REQUEST_DATA = 'NOTES_REQUEST_DATA'
export const NOTES_RECEIVE_DATA = 'NOTES_RECEIVE_DATA'
export const NOTES_ERROR = 'NOTES_ERROR'

export const JOURNAL_REQUEST_DATA = 'JOURNAL_REQUEST_DATA'
export const JOURNAL_RECEIVE_DATA = 'JOURNAL_RECEIVE_DATA'
export const JOURNAL_ERROR = 'JOURNAL_ERROR'
